
## DAY SCHEDULE COLORS 
# MACHINE_AVAILABLE_COLOR = (255,0,0)
# MACHINE_ASSIGNED_COLOR = (127,127,127)
# MACHINE_NOT_AVAILABLE_COLOR = (0,0,0)

# GRAY_COLORS 

DAY_MACHINE_NON_WORKING_COLOR = 0   ### Like night hours / non working hrs
DAY_MACHINE_WORKING_COLOR = 200
DAY_MACHINE_ASSIGNED_COLOR = 127


## ORDER / JOB COLORS
DELAY_COLOR = 30
OPERATION_COLOR = 200


DISPLAY_ASSIGNED_CYCLE_COLOR = (94,49,28)
DISPLAY_ASSIGNED_DELAY_COLOR = (112,124,34)
DISPLAY_NOT_ASSIGNED_WORKING_COLOR = (255,162,173)
DISPLAY_NOT_ASSIGNED_NON_WORKING_COLOR = (225,248,255)

DISPLAY_ASSIGNED_ALTERNATE_CYCLE_COLOR = (123,89,255)
DISPLAY_ASSIGNED_ALTERNATE_DELAY_COLOR = (158,142,255)



#### OPERATIONS DEFINED
# 1. Take first operation of order     
# 2. BREAK_OPRATION_AT_WORK_HR_FOR_NEXT_DAY
# 3. Or assign work hr for operation1
# 4. TRY_EXTENDING_DELAY_TO_CONSUME_NON_WORKING_HOURS_OF_NIGHT if Yes OK. if not STEP_NEXT_HR_INCREMENT
#       For loop min to max delay hr so that next operation working should overlap  color on color  

# 
# STEP_NEXT_HR_INCREMENT
