
## DAY SCHEDULE COLORS 
# MACHINE_AVAILABLE_COLOR = (255,0,0)
# MACHINE_ASSIGNED_COLOR = (127,127,127)
# MACHINE_NOT_AVAILABLE_COLOR = (0,0,0)

# GRAY_COLORS 

DAY_MACHINE_NON_WORKING_COLOR = 0   ### Like night hours / non working hrs
DAY_MACHINE_WORKING_COLOR = 200
DAY_MACHINE_ASSIGNED_COLOR = 127


## ORDER / JOB COLORS
DELAY_COLOR = 30
OPERATION_COLOR = 200